spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create  # Corrigido de db-auto para ddl-auto
    properties:
      hibernate:
        format_sql: true  # Corrigido de format_sql:true para format_sql: true
  h2:
    console:
      enabled: true  # Corrigido de enable para enabled
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
